name: Python application test with Github Actions

on: [push]

jobs:
  builds:
    steps:
    - runs-on: ubuntu-latest
    - name: Install dependencies
      run: |
        make install
    - name: Lint with pylint
      run: |
        make lint
    - name: Test with pytest
      run: |
        make test
    - name: Format code
      run: |
        make format
  
